language: java
jdk:
- oraclejdk8
#- oraclejdk7
#- openjdk7
env:
  global:
  # SONATYPE_USERNAME
  - secure: "EiwZ8r5ZRnykCho92c/lFCJbiB5KoStfetmYPJuUsmN/lzh5MPCij8czub2YbhgpYH9IYzO0uNP5lJ1SEI/3BWGSXIQaNIFHrD2mJTX7Z2FL/LMnoY9uBlaQpLFspEeL9tkxv7At5POnYbSi/oSxPjw9zqVc/OdPEYiAyHIivqg="
  # SONATYPE_PASSWORD
  - secure: "cZvhzqlyq5yQc3daIJJzIyyTBvodXpT6FhQ55iq7ufd19kBqy7nRMIx2A6H0s1m9nW7kOOe9vHLPf12m99+JDyT/Q6IA5t+4OMJwL2btpP5AcBMyr9FU4859MGrAH9zWeliYOiq+s6H4zsekHJDoO/CxafzaK70Umxit8qgfijU="
  # GPG_PASSPHRASE
  - secure: "DURHYTSX9T78zNHu5qNEmWLBWT4Lccpi/Rklpjulsvh0EkB6dlrnejB/dQPYkIwRSlhJ/AqiiQypFqSqAd94jvqk0XKIstI0knHoDobN1cIqcJNan0Apb9ICd+iPYzxLmK4gz7Jq81P9GoicuPMg+Mi1HVPcvkoTfpPJseccfaM="
  # ENC_SECRET
  - secure: "arj7wyqKyzxTwCWh8j55HDOpp+Xgidl9RP+Rr06hR246NNBq51nIvgAwfeJbDUZKr/oyNzJFkjQyAC4DX5uxhPsR3TjgApR+NQLkoOlnoFFRvRSXQ2fEiwC5rWDwV6eaVYK84Ec5DqISlW4eoACWYMUUp3jWfQ34b0+jtIXO1Vw="  
before_install:
- mkdir gpg
- openssl aes-256-cbc -k "$ENC_SECRET" -in deploy-files/secring.gpg.enc -d -a -out gpg/secring.gpg
- openssl aes-256-cbc -k "$ENC_SECRET" -in deploy-files/pubring.gpg.enc -d -a -out gpg/pubring.gpg
after_success:
- java_version=$(javac -version) 
#- "[[ $java_version =~ 1.8 ]] && mvn deploy -DskipTests=true -B -V --settings deploy-files/settings.xml"
- mvn deploy -DskipTests=true -B -V --settings deploy-files/settings.xml
